# Generated by Django 3.0 on 2020-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('udalec', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='rabs/imag/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
