# Generated by Django 3.0 on 2020-05-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0002_auto_20200526_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='bows/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
