# Generated by Django 3.0 on 2020-05-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0004_auto_20200527_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth',
            field=models.DateField(),
        ),
    ]
