# Generated by Django 3.0 on 2020-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0005_auto_20200528_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='draft',
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth',
            field=models.CharField(max_length=100),
        ),
    ]
