# Generated by Django 3.0 on 2020-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0007_auto_20200529_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='age1',
            new_name='ageo',
        ),
    ]
