# Generated by Django 3.0 on 2020-05-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0009_auto_20200529_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth',
            field=models.DateField(),
        ),
    ]
