# Generated by Django 3.0 on 2020-05-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0011_auto_20200529_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='udalec',
            new_name='udalenka',
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth',
            field=models.DateField(blank=True),
        ),
    ]
