# Generated by Django 3.0 on 2020-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0012_auto_20200529_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='adres',
        ),
        migrations.AddField(
            model_name='employee',
            name='dom',
            field=models.IntegerField(default=15, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gorod',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='ulitsa',
            field=models.CharField(default=13, max_length=100),
            preserve_default=False,
        ),
    ]
