# Generated by Django 3.0 on 2020-05-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0013_auto_20200529_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AlterField(
            model_name='employee',
            name='dom',
            field=models.CharField(max_length=100),
        ),
    ]
