# Generated by Django 3.0 on 2020-05-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0015_auto_20200529_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
