# Generated by Django 3.0 on 2020-05-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0017_auto_20200529_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('техник', 'техник'), ('техник', 'техник'), ('техник', 'техник')], max_length=100),
        ),
    ]
