# Generated by Django 3.0 on 2020-05-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0018_auto_20200529_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('cow', 'cow'), ('gow', 'gow'), ('bow', 'bow')], max_length=100),
        ),
    ]
