# Generated by Django 3.0 on 2020-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0021_auto_20200602_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='kvartira',
            field=models.IntegerField(default=34, max_length=100),
            preserve_default=False,
        ),
    ]
