# Generated by Django 3.0 on 2020-06-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srk', '0023_auto_20200602_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('Техник', 'Техник'), ('Бухгалтер', 'Бухгалтер'), ('Программист', 'Программист')], max_length=100, null=True),
        ),
    ]
